### ISSUE TITLE
Suggestion: Remove Quick Start

### ISSUE THREAD

**Issue by jamesjuett** [eecs280staff/tutorials#174]
We've had some previous discussion about the "quick start" on the main tutorials page. After a few terms using the tutorials, my anecdotal experience with several students in EECS 280 is:

1.  - The quick start sends new students to an IDE tutorial first, which then bounces them back to CLI tools setup (assuming they notice the prerequisites section and follow the links there). This isn't an intuitive flow through the tutorials.
2.  - The quick start encourages students to only work through the parts mentioned there (many do not engage with the CLI or Makefile tutorials). If we want students to work through those, this is a problem. And, if we don't want students to work through those, we should just remove them from the setup sequence.

#173, if merged, would partly address point 1 but not point 2 (and probably makes it worse, since it just means we have a partial setup sequence and a full setup sequence).

I'll acknowledge this is a repeat of concerns I previously shared about the quick start when we designed the current front page. At the time, I was unsure whether it would be a significant issue. However, I'm bringing this up again after a few terms since it has proven to cause confusion for some students.

The tutorials may be used by lots of people in different contexts. But, I think we need to optimize for our students.

**Comment by nskh** [comment]
I've noticed this issue as well; students seem to have installed VS Code but not worked with their command line, or they're using IDE workflows learned from previous classes where they just click "Play" in Visual Studio/XCode. Promoting the CLI setup/walkthroughs and Makefile tutorials to the top of the page should help, at the margins, get more students to work through those instead of missing them.

**Comment by jamesjuett** [comment]
Closed via #175
