### ISSUE TITLE
GitLab Retirement

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#18]
It looks like the University will retire its GitLab SaaS in favor of some sort of site license for GitHub ([ITS docs](https://its.umich.edu/communication/collaboration/github/help-resources)).  We'll need to update the Version Control Tutorial.

Don't forget to do a recursive search of ALL EECS 280 repos looking for case insensitive `gitlab`.  Also, we need to make sure out instructions *default* to private repos for students.

**Comment by zjweiss** [comment]
I also support the transition to GitHub, as its more widely known and accepted in industry, and it may be easier to send someone interested in a student's projects a GitHub.com link, rather than a gitlab.eecs.umich.edu link (aka internship recruiters interested in projects a student has done).

FWIW,  in my experience most students naturally transition to GitHub post 280, and very few students use GitLab in ULCS classes. I was one of the few people that I knew who used the gitlab.eecs.umich.edu site, until I switched over to GitHub this semester.

Also, GitHub also has many tools that make it easier for newer programmers. Namely, [GitHub Desktop](https://desktop.github.com/) can be helpful for students getting used to the Git workflow. I know that GitHub desktop, makes it easier for students to deal with merge issues. Introducing GitHub Desktop, may be more of a disservice than a service though, as I think have the CLI Git experience is invaluable.

**Comment by zjweiss** [comment]
The largest issue that I see with GitHub, is that the SSH key setup is considerably more difficult than the HTTPS login (that GitLab supports and GitHub used to support), although these issues may be mitigated by recommending GitHub desktop.

GitHub Desktop is pretty ready to go out of the box with minimal setup, so that is a plus.

I think GitHub desktop might be a good option as it doesn't require the SSH keys and it is GitHub, but it comes at the expense of students learning the Git CLI.

What are your thoughts?

**Comment by awdeorio** [comment]
We adapted the EECS 280 GitLab tutorial to GitHub in EECS 485.  It will be live soon.  I'll link it here and we can discuss.

**Comment by awdeorio** [comment]
EECS 485 has posted their [update of the Git tutorial](https://eecs485staff.github.io/p1-insta485-static/setup_git.html).  Take a look!

**Comment by zjweiss** [comment]
I think the updated tutorial looks good!
