### ISSUE TITLE
VS Code Nuclear Option

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#92]
VS Code leaves files in many places: project, `~/.vscode`, system standard configuration location in home directory, et al.  I've run into some situations where the REAL way to restart is to delete all VS Code data.  We should include this in the Restart section.  Maybe call it "delete all configuration and extensions" or something.

Here's the Microsoft docs: https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall

I had to do this on multiple machines over the last week.

**Comment by ohjuny** [comment]
Are you imagining replacing the current [VS Code Restart](https://eecs280staff.github.io/tutorials/setup_vscode.html#restart) to instruct students to reinstall VS Code (instead of just deleting the directory), or adding on to it with something like:
"if you tried the above (deleting the directory) and are still facing issues, then consider reinstalling VS Code. (... instructions ...)"

**Comment by awdeorio** [comment]
How about starting with "try reconfiguring" and then later say "if you need to you can delete the directory AND configuration".
