### ISSUE TITLE
VS Code sanity checks

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#93]
We might save some headaches for students by adding a few prerequisites to the VS Code tutorial.  In my experience, these would apply in particular to students who've used VS Code before but something changed on their machine.

macOS make sure you have a the XCode tools installed and link to instructions.
```console
$ g++ --version
$ lldb --version
```

Linux / WSL make sure you have g++ and gdb installed and link to instructions for installing
```console
$ g++ --version
$ gdb --version
```

**Comment by ohjuny** [comment]
Are you imagining replacing the current [VS Code Restart](https://eecs280staff.github.io/tutorials/setup_vscode.html#restart) to instruct students to reinstall VS Code (instead of just deleting the directory), or adding on to it with something like:
"if you tried the above (deleting the directory) and are still facing issues, then consider reinstalling VS Code. (... instructions ...)"
