### ISSUE TITLE
GitHub Access

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#97]
The Version Control tutorial doesn't cover how to authenticate so that you can *write* to a repo.  For that, you need either SSH keys or a GitHub Access token.  I think that most students will find Access Tokens easier.

In office hours today, I had a student run into this problem.  Furthermore, she needed to use the "classic token" to get it to work, not the "fine-grain token".

**Comment by TheOmid** [comment]
I wrote a rough draft for the tutorial. I decided to make the main section about personal access tokens because I also think students will find it easier. SSH option is presented as an alternative if they are curious (using GitHub's tutorial, but if needed, I can write it up). The main reason I did not write both tutorials is I though if we present students with two viable options, then they have to make an arbitrary choice.

A couple of notes:

1. Maybe we should just include a tutorial for downloading [Git Credential Manager](https://docs.github.com/en/enterprise-server@3.4/get-started/getting-started-with-git/updating-credentials-from-the-macos-keychain#updating-your-credentials-via-keychain-access) which takes care of all of it. It makes it much easier for students IMO.
2. I think we should tell students to set an expiration date for their password. Having no expiration is a security risk. The only concern is that it can create a hassle for them to renew it. 90 days is also not enough. Ideally, we can ask students to set it as the last day of classes, but for now, I have put it down January 1st of next year.
3. I think we should revamp the whole tutorial and center it around pushing project 2 to GitHub. Since this is out of the scope of this issue, I did not change other areas besides connecting to remote repo. Student's might get confused that the rest of the project is for Justin's EECS 485 project 1.
4. I think the MacOS pitfall and expiration note can be more clear. LMK if you have suggestions for that

I personally use SSH. I tested this with a new GitHub account, and the tutorial worked.
