### ISSUE TITLE
Require WSL 2

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#98]
WSL 1 and Ubuntu 22.04 are incompatible.  This is from @jamesjuett :

The intractable VS code debugging issue with "failed to set controlling terminal" is solved (sort of)!  The problem manifests when students have WSL 1 rather than WSL 2. There's an incompatibility with newer versions of Ubuntu (I think - I'm assuming that's why we're starting to see it this term but haven't before). Some details here: https://github.com/microsoft/WSL/issues/8356

The fix is to upgrade to WSL 2. There are two ways to do this.
- Their Windows version must be new enough. Windows 11 or Windows 10 Build 19041 or newer.
- Need to have virtualization enabled. Might need to do this in BIOS. (Although I see that less and less these days.)
- Need to have Windows Virtual Machine Platform enabled.
- May need to do step 4 here: https://learn.microsoft.com/en-us/windows/wsl/install-manual
- Finally set default version to WSL 2: https://learn.microsoft.com/en-us/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2

We should add a sanity check and require this.

**Comment by jamesjuett** [comment]
One thing that's slightly imprecise in what I originally said - it's not that Ubuntu 22.04 itself is incompatible, but that with it you'll end up with a newer version of gdb that is incompatible.

I'm not sure if we'll end up with many (or any?) students who can't upgrade to WSL 2. If they're on a very old laptop, can't update to a new enough windows version, or can't enable virtualization. I haven't met any students where that's the case.

The best approach is likely to:
 - Require WSL 2 in the tutorials (and add the check that `wsl -l -v` run from PowerShell shows version 2).
 - Add instructions for upgrading from WSL 1 to WSL 2. These should probably be in a separate document that we can link to, so that they don't confuse people working through the normal setup tutorial.
 - Handle any obscure cases where people are having difficulty getting WSL 2 in office hours.

**Comment by awdeorio** [comment]
Agreed!

**Comment by jamesjuett** [comment]
Just putting this here to record it somewhere. The deficit in WSL 1 is tracked [here](https://github.com/microsoft/WSL/issues/547). Not clear it would ever be fixed.
